postgres:
  image: postgres
rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
web:
  build: .
  command: ./_scripts/run_localserver.sh
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - postgres
    - rabbitmq
worker:
  build: .
  command: ./_scripts/run_celery_local.sh
  environment:
    C_FORCE_ROOT: 1
  volumes:
    - .:/code
  links:
    - postgres
    - rabbitmq
